### ISSUE TITLE
res.writeHead in Express 4.x

### ISSUE THREAD

**Issue by Dreyer** [mozilla-services/express-hawkauth#2]
Does this method which modifies the `res.writeHead` in order to 'sign' the response still work in Express 4.x?

The `res.body` appears to be `undefined` when `res.writeHead` is called.

https://github.com/mozilla-services/express-hawkauth/blob/master/lib/hawk.js#L168

``` javascript

        // ...
        setUser(req, res, credentials, function() {
          /* Make sure we don't decorate the writeHead more than one time. */
          if (res._hawkEnabled) {
            next();
            return;
          }

          var writeHead = res.writeHead;
          res._hawkEnabled = true;
          res.writeHead = function hawkWriteHead() {
            var header = Hawk.server.header(
              credentials, artifacts, {
                payload: res.body,
                contentType: res.get('Content-Type')
              });
            // The server signs its responses so the client can check they're
            // coming from there.
            res.setHeader("Server-Authorization", header);
            writeHead.apply(res, arguments);
          };
          next();
        });
        // ...
```

I'm using a workaround which modifies `res.send` but not sure if there is a preferred way of doing this:
https://github.com/strongloop/express/issues/2444

**Comment by Natim** [comment]
> Does this method which modifies the writeHead in order to sign the payload still work in Express 4.x?

We are using it with success here: https://github.com/mozilla-services/loop-server/blob/master/package.json#L25-L26

> The res.body appears to be undefined when writeHead is called.

Yes this may happen.
Hawk doesn't necessarily needs the body to work, if the body is undefined, then the Server-Authorization will not sign the content.

In your case it could be interesting to sign the content. We probably need to work on that. Could you please start to write some tests that highlight what we should fix?

As far as I see here, we should have one that makes sure that if there is some payload the Server-Authorization contains it. Also we need one to make sure when we use res.sendFile the file content is used as payload.

**Comment by Dreyer** [comment]
For the sake of posterity, I published a middleware that I've been using for some time now based on the starting point you guys provided: [Dreyer/express-hawk](https://github.com/Dreyer/express-hawk)
